language: rust

sudo: false

rust:
    - nightly

addons:
  apt:
    packages:
      - nasm

cache: cargo

before_script:
  - curl https://sh.rustup.rs -sSf | sh -s -- --default-toolchain=$TRAVIS_RUST_VERSION -y
  - source ~/.cargo/env
  - rustup component add rust-src
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/rustfmt || cargo install rustfmt)
  - (test -x $HOME/.cargo/bin/xargo || cargo install xargo)
  - cargo install-update -a

script:
  - make
